functionsGradleVersion = 0.51.0
functionsRuneVersion = 0.30.0
functionsTypescriptRuntimeVersion = 0.289.0
functionsTypescriptVersion = 0.1244.0
nodeInstallationVersion = 24.16.0
repositoryName = crisis-logistics-functions-v2
repositoryOrg = Atamer Systems-976c6b
repositoryProject = Crisis Logistics Command System
repositoryRid = ri.stemma.main.repository.48e022c0-39bf-4d9b-9aa9-af766b769064
