canEnforceMinimumPythonVersion = true
condaSolveImplementation = hawk
enableCodeAssistEnvironmentCaching = true
enableLegacyFallback = false
envPackingLogicVersion = 2
org.gradle.caching = true
org.gradle.vfs.watch = false
palantirModelsVersion = 0.2281.0
rootProjectName = logistics_pipelines
systemProp.http.connectionTimeout = 600000
systemProp.http.socketTimeout = 600000
systemProp.org.gradle.internal.http.connectionTimeout = 600000
systemProp.org.gradle.internal.http.socketTimeout = 600000
transformsDefaultBranchName = master
transformsLangPythonPluginVersion = 1.1166.0
transformsRepoOrg = Atamer Systems-976c6b
transformsRepoPath = /Atamer Systems-976c6b/Crisis Logistics Command System/logistics_pipelines
transformsRepoProject = Crisis Logistics Command System
transformsRepoRid = ri.stemma.main.repository.c37e68e3-9f1f-4b0a-aecf-c326f008782a
transformsVersion = 10.118.0
useCondaLocksForPlatforms = linux-64
useDefaultPython = false
useHawkAsDefaultSolver = true
useHawkUvSolver = true
useIncrementalSolve = true
