---
mappings:
- alias: "/Atamer Systems-976c6b/Crisis Logistics Command System/02_clean_derived/derived_resources"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.6c91fc7d-5541-4fa6-98cb-a2ea9aaeda94"
- alias: "/Atamer Systems-976c6b/Crisis Logistics Command System/02_clean_derived/nearby_infrastructure"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.0188eb65-eb2f-4b4f-8a72-c0003eb00b7b"
- alias: "/Atamer Systems-976c6b/Crisis Logistics Command System/02_clean_derived/validated_logistics_hubs"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.4bc28207-5239-4f47-99f5-805da54d8e89"
- alias: "ri.foundry.main.dataset.4f3670e9-107e-423c-a3fc-cc95da5ec382"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.4f3670e9-107e-423c-a3fc-cc95da5ec382"
- alias: "ri.foundry.main.dataset.89addc0e-00be-4277-86d8-d5ba5a9f9f39"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.89addc0e-00be-4277-86d8-d5ba5a9f9f39"
- alias: "ri.magritte..source.0049ef11-1810-4389-96bb-de55ac0f528f"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.magritte..source.0049ef11-1810-4389-96bb-de55ac0f528f"
